### ISSUE TITLE
登录失败的情况

### ISSUE THREAD

**Issue by Xi030010** [vouv/srun#1]
提示 ”登录失败：login-error \n msg：login-error“
这是啥情况呀，系统是macOS

**Comment by vouv** [comment]
> 提示 ”登录失败：login-error \n msg：login-error“
> 这是啥情况呀，系统是macOS

请看文件`cmd/srun/srun.go`85行，这个错误是学校服务器返回的，一般来说账号密码正确的话重试几次应该没问题。
