### ISSUE TITLE
登录失败：login_error

### ISSUE THREAD

**Issue by fA1sEr** [vouv/srun#2]
linux下试了十几次，都是这样
关于账号密码，也删json文件重输了几次，确定没有错

**Comment by vouv** [comment]
> linux下试了十几次，都是这样
> 关于账号密码，也删json文件重输了几次，确定没有错

`srun -d login`试一试，看报什么错

**Comment by fA1sEr** [comment]
> > linux下试了十几次，都是这样
> > 关于账号密码，也删json文件重输了几次，确定没有错
> 
> `srun -d login`试一试，看报什么错

[D]  {login_error login_error  INFO Error锛宔rr_code=2 10.108.17.150}

**Comment by vouv** [comment]
> > > linux下试了十几次，都是这样
> > > 关于账号密码，也删json文件重输了几次，确定没有错
> > 
> > 
> > `srun -d login`试一试，看报什么错
> 
> [D] {login_error login_error INFO Error锛宔rr_code=2 10.108.17.150}

不好意思，这应该是个bug。我把程序更新了v0.1.6，下载最新版本后稍后`srun account`切换一下常用登录网试试，应该没问题了

**Comment by fA1sEr** [comment]
> > > > linux下试了十几次，都是这样
> > > > 关于账号密码，也删json文件重输了几次，确定没有错
> > > 
> > > 
> > > `srun -d login`试一试，看报什么错
> > 
> > 
> > [D] {login_error login_error INFO Error锛宔rr_code=2 10.108.17.150}
> 
> 不好意思，这应该是个bug。我把程序更新了v0.1.6，下载最新版本后稍后`srun account`切换一下常用登录网试试，应该没问题了

登录成功了。
另外发现一个问题，export http_proxy=xxxxx后，运行srun报错（等待很久之后）“[E]  请求错误”

**Comment by vouv** [comment]
> > > > > linux下试了十几次，都是这样
> > > > > 关于账号密码，也删json文件重输了几次，确定没有错
> > > > 
> > > > 
> > > > `srun -d login`试一试，看报什么错
> > > 
> > > 
> > > [D] {login_error login_error INFO Error锛宔rr_code=2 10.108.17.150}
> > 
> > 
> > 不好意思，这应该是个bug。我把程序更新了v0.1.6，下载最新版本后稍后`srun account`切换一下常用登录网试试，应该没问题了
> 
> 登录成功了。
> 另外发现一个问题，export http_proxy=xxxxx后，运行srun报错（等待很久之后）“[E] 请求错误”

srun是通过在校园网环境内访问10.0.0.55获取信息的，使用代理可能会导致连不上

**Comment by fA1sEr** [comment]
> > > > > > linux下试了十几次，都是这样
> > > > > > 关于账号密码，也删json文件重输了几次，确定没有错
> > > > > 
> > > > > 
> > > > > `srun -d login`试一试，看报什么错
> > > > 
> > > > 
> > > > [D] {login_error login_error INFO Error锛宔rr_code=2 10.108.17.150}
> > > 
> > > 
> > > 不好意思，这应该是个bug。我把程序更新了v0.1.6，下载最新版本后稍后`srun account`切换一下常用登录网试试，应该没问题了
> > 
> > 
> > 登录成功了。
> > 另外发现一个问题，export http_proxy=xxxxx后，运行srun报错（等待很久之后）“[E] 请求错误”
> 
> srun是通过在校园网环境内访问10.0.0.55获取信息的，使用代理可能会导致连不上

好的，谢谢。
