### ISSUE TITLE
 login_error  Nas type not found.

### ISSUE THREAD

**Issue by wsh122333** [vouv/srun#6]
# ./srun-linux -d login

DEBU[2020-08-01 13:01:48] 读取账号信息: /home/xxx/.srun/account.json     
INFO[2020-08-01 13:01:48] 尝试登录: 校园网                               
DEBU[2020-08-01 13:01:48] Username: xxx
DEBU[2020-08-01 13:01:48] Acid: 0
DEBU[2020-08-01 13:01:48] 登录失败: login_error                          
DEBU[2020-08-01 13:01:48] {login_error login_error  Nas type not found. xx.xx.xx.xx}
ERRO[2020-08-01 13:01:48] 登录失败

请问一下这种情况是什么问题呢 @vouv ，谢谢！

**Comment by vouv** [comment]
> # ./srun-linux -d login
> DEBU[2020-08-01 13:01:48] 读取账号信息: /home/xxx/.srun/account.json
> INFO[2020-08-01 13:01:48] 尝试登录: 校园网
> DEBU[2020-08-01 13:01:48] Username: xxx
> DEBU[2020-08-01 13:01:48] Acid: 0
> DEBU[2020-08-01 13:01:48] 登录失败: login_error
> DEBU[2020-08-01 13:01:48] {login_error login_error Nas type not found. xx.xx.xx.xx}
> ERRO[2020-08-01 13:01:48] 登录失败
> 
> 请问一下这种情况是什么问题呢 @vouv ，谢谢！

更新了下
